version: 2

sources:
  - name: AUTOVAULT_PUBLIC
    database: AUTOVAULT
    schema: PUBLIC
    tables:
      - name: TRANSACTIONS_V1
        columns:
          - name: CUSTOMER_ID
            description:  "Business key"
            tests:
              - unique
              - not_null
          - name: PRODUCT_ID
            description:  "Business key"
            tests:
              - not_null
          - name: DATE_OF_SESSION
            description:  "Business key"
            tests:
            description:  "Business key"
            tests:
              - unique
          - name: PRODUCT_ID
            description:  "Business key"
            tests:
            description:  "Business key"
            tests:
              - unique
