version: 2

sources:
  - name: AUTOVAULT_ADOBE
    database: AUTOVAULT
    schema: ADOBE
    tables:
      - name: TRANSACTIONS_V1
  - name: AUTOVAULT_PUBLIC
    database: AUTOVAULT
    schema: PUBLIC
    tables:
      - name: CUSTOMERS_V1
      - name: CUSTOMER_VISITS_V1
      - name: PRODUCTS_V1
