version: 2

sources:
  - name: AV
    database: AUTOVAULT
    schema: PUBLIC
    tables:
      - name: CUSTOMERS
      - name: PRODUCTS
      - name: TRANSACTIONS
      - name: CUSTOMER_VISITS
      - name: TOTAL_CUST_VISITS